# Path Speed Boost Plugin Configuration

# Set the speed multiplier for players here:
player-speed-multiplier: 1.4
# Set the speed multiplier for mounts (horses and pigs) here:
mount-speed-multiplier: 1.4
# Enable or disable path speed boost for players:
enable-path-speed-boost: true

# Adjust the speed reduction multiplier for players walking through tall grass.
tall-grass-reduction-multiplier: 0.5

# Enable or disable tall grass speed reduction for players:
enable-tall-grass-speed-reduction: true

# Enable or disable mount path speed boost:
enable-mount-path-speed-boost: true
