name: PathSpeedBoost
version: ${project.version}
main: org.b0b0bo.pathspeedboost.Main
authors:
  - b0b0b0
  - 1050TI_top
  - OverwriteMC
description: Increases player speed by a configurable percentage when moving on a dirt path.
commands:
  psb:
    description: Main command for the Path Speed Boost Plugin.
    usage: /<command> reload
    aliases: [pathspeedboost]
    permission: pathspeedboost.reload
permissions:
  pathspeedboost.reload:
    description: Allows the user to reload the Path Speed Boost Plugin configuration.
    default: op
